import './glossary-format.mjs';
import {sanitizeImage} from './image-codec.mjs';
const format=globalThis.CARDSTUDIO_GLOSSARY,MAX_IMAGE=15*1024*1024;
export const hash=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',typeof value==='string'?new TextEncoder().encode(value):value)),n=>n.toString(16).padStart(2,'0')).join('');
const uuid=()=>crypto.randomUUID(),token=()=>uuid()+uuid(),stamp=()=>new Date().toISOString();
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status})};
const str=(s,n,label)=>{if(s==null)return '';if(typeof s!=='string'||s.length>n)fail(label+'格式或长度无效');return s};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json;charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Access-Control-Allow-Origin':'*',...headers}});
const query=(env,sql,...args)=>env.DB.prepare(sql).bind(...args);
const first=(env,sql,...args)=>query(env,sql,...args).first();
const all=async(env,sql,...args)=>(await query(env,sql,...args).all()).results||[];
async function bytes(request,max){const reader=request.body?.getReader();if(!reader)return new Uint8Array();let n=0,parts=[];while(true){const r=await reader.read();if(r.done)break;n+=r.value.length;if(n>max){await reader.cancel();fail('提交内容超过大小限制',413)}parts.push(r.value)}const out=new Uint8Array(n);let p=0;for(const part of parts){out.set(part,p);p+=part.length}return out}
async function body(request){if(!request.headers.get('content-type')?.includes('application/json'))fail('提交格式无效',415);try{return JSON.parse(new TextDecoder().decode(await bytes(request,5*1024*1024)))}catch(e){if(e.status)throw e;fail('提交内容无法读取')}}
function rawToken(request){return request.headers.get('authorization')?.replace(/^Bearer /,'')||request.headers.get('cookie')?.match(/(?:^|;\s*)kadi_visitor=([A-Za-z0-9-]{40,100})(?:;|$)/)?.[1]||''}
async function actor(request,env){const raw=rawToken(request);if(!raw)return null;const s=await first(env,'SELECT * FROM kadi_sessions WHERE id=? AND revoked=0 AND expires_at>?',await hash(raw),Date.now());return s&&['owner','visitor','collaborator','invite-read','invite-submit'].includes(s.role)?s:null}
function allowed(user,permission,kind){return user?.role==='owner'||user?.role==='collaborator'&&JSON.parse(user.permissions||'[]').some(p=>p===permission||p===permission+':'+kind)}
async function requireActor(request,env,permission,kind){const user=await actor(request,env);if(!user)fail('请先填写昵称后投稿',401);if(permission&&!allowed(user,permission,kind))fail('这台设备没有此项管理权限',403);return user}
async function settings(env){const row=await first(env,"SELECT value FROM kadi_settings WHERE key='policy'");return row?JSON.parse(row.value):{submissionMode:'open',readMode:'public'}}
async function canRead(request,env){const policy=await settings(env);if(policy.readMode==='invite'&&!['owner','collaborator','invite-read','invite-submit'].includes((await actor(request,env))?.role))fail('这份资料库目前仅向受邀伙伴开放',401)}
async function quota(env,id,n,limit=40){const key=id+':'+stamp().slice(0,10);const row=await query(env,'INSERT INTO kadi_counters(id,count) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET count=count+excluded.count WHERE count+excluded.count<=? RETURNING count',key,n,limit).first();if(!row||row.count>limit)fail('今日提交较多，请稍后再试或联系管理员',429)}
async function permitSubmission(request,env,user,n){const p=await settings(env);if(p.submissionMode==='closed')fail('管理员暂时关闭了投稿，资料仍可取用',403);if(p.submissionMode==='invite'&&!['owner','collaborator','invite-submit'].includes(user.role))fail('目前仅接受受邀伙伴投稿',403);if(user.role!=='owner'){await quota(env,user.actor_id,n);const ip=request.headers.get('cf-connecting-ip');if(ip)await quota(env,'submission-ip:'+await hash(ip),n,200)}}
// Reserve unique binary bytes atomically before writing R2. Failed or withdrawn
// submissions also retain their charge, so creating new nicknames cannot fill
// storage beyond the budget. Existing originals/history are counted once.
async function reserveImages(env,images){
 const writes=[];if(!await first(env,"SELECT value FROM kadi_settings WHERE key='image-budget-v1'")){
  const keys=await all(env,'SELECT blob_key AS key FROM kadi_versions WHERE blob_key IS NOT NULL UNION SELECT thumb_key FROM kadi_versions WHERE thumb_key IS NOT NULL UNION SELECT blob_key FROM kadi_submissions WHERE blob_key IS NOT NULL UNION SELECT thumb_key FROM kadi_submissions WHERE thumb_key IS NOT NULL');
  for(const {key} of keys){const object=await env.BUCKET.head(key);if(object)writes.push(query(env,'INSERT OR IGNORE INTO kadi_settings(key,value) VALUES(?,?)','stored-image:'+key,String(object.size)))}
  writes.push(query(env,"INSERT OR IGNORE INTO kadi_settings(key,value) VALUES('image-budget-v1','1')"));
 }
 for(const [key,bytes] of images)writes.push(query(env,'INSERT OR IGNORE INTO kadi_settings(key,value) VALUES(?,?)','stored-image:'+key,String(bytes.length)));
 const gate=uuid();writes.push(query(env,"INSERT INTO kadi_guards(id,valid) VALUES(?,CASE WHEN (SELECT COALESCE(SUM(CAST(value AS INTEGER)),0) FROM kadi_settings WHERE key LIKE 'stored-image:%')<=536870912 THEN 1 ELSE 0 END)",gate),query(env,'DELETE FROM kadi_guards WHERE id=?',gate));
 try{await env.DB.batch(writes)}catch(e){if(/constraint|guard/i.test(e.message))fail('素材存储空间已满，请联系管理员；原图仍保留在本机',429);throw e}
}
function publicItem(row){const p=JSON.parse(row.payload);return {...p,id:row.id,publicId:row.id,publicRevision:row.revision,author:row.author,status:row.status,updatedAt:row.updated_at,...(row.blob_key?{hash:row.blob_key,url:'/api/repository/files/'+row.blob_key,thumbnailUrl:'/api/repository/files/'+row.thumb_key}:{} )}}
async function catalog(request,env){await canRead(request,env);const rows=await all(env,"SELECT * FROM kadi_records WHERE status='published' ORDER BY kind,name,id");return {schema:'cardstudio-public-catalog-v1',revision:await hash(JSON.stringify(rows.map(r=>[r.id,r.revision]))),terms:rows.filter(r=>r.kind==='term').map(publicItem),assets:rows.filter(r=>r.kind==='asset').map(publicItem),counts:{terms:rows.filter(r=>r.kind==='term').length,assets:rows.filter(r=>r.kind==='asset').length}}}
function attribution(raw,user){return {source:str(raw.source,1000,'来源'),license:str(raw.license||'允许用于卡递作品，保留署名',500,'使用范围'),author:user.name}}
function termItem(raw,user){const payload=format.normalizeTerm(raw);if(!payload.description.trim())fail('请填写词条的完整定义');return {payload:{...payload,...attribution(raw,user),namespace:str(raw.namespace,80,'规则体系')},targetId:raw.targetId||raw.repositoryId||raw.publicId||null}}
async function assetItem(request,env,user){
 const data=await bytes(request,MAX_IMAGE+65536);let form;try{form=await new Request(request.url,{method:'POST',headers:{'Content-Type':request.headers.get('content-type')||''},body:data}).formData()}catch{fail('图片提交格式无效')}
 const file=form.get('file');if(!file||typeof file==='string'||file.size>MAX_IMAGE)fail('请选择 15MB 内图片',413);let raw;try{raw=JSON.parse(String(form.get('metadata')||'{}'))}catch{fail('素材信息格式无效')}
 const name=str(raw.name,120,'名称').trim();if(!name)fail('请填写素材名称');let safe;try{safe=await sanitizeImage(new Uint8Array(await file.arrayBuffer()))}catch(e){fail(e.message)}
 const blobKey=await hash(safe.clean),thumbKey=await hash(safe.thumbnail),payload={id:str(raw.id||uuid(),128,'素材编号'),name,category:['template','frame','icon','decoration','illustration','texture','back','other'].includes(raw.category)?raw.category:'other',tags:str(raw.tags,500,'标签'),description:str(raw.description,4000,'说明'),...attribution(raw,user),mime:safe.mime,width:safe.width,height:safe.height,bytes:safe.clean.length};
 const images=new Map([[blobKey,safe.clean],[thumbKey,safe.thumbnail]]);await reserveImages(env,images);for(const [key,image] of images)if(!await env.BUCKET.head(key))await env.BUCKET.put(key,image,{httpMetadata:{contentType:'image/png'}});return {payload,blobKey,thumbKey,targetId:raw.targetId||raw.repositoryId||raw.publicId||null,expected:raw.expectedRevisions||{}};
}
function audit(env,user,action,id,detail=''){return query(env,'INSERT INTO kadi_audit(id,actor_id,action,record_id,detail,created_at) VALUES(?,?,?,?,?,?)',uuid(),user.actor_id,action,id,detail,stamp())}
async function submit(request,env,user,kind,items,prepaid=false){
 if(!items.length||items.length>40)fail('一次可投稿 1 至 40 项');if(!prepaid)await permitSubmission(request,env,user,items.length);const writes=[],out=[];
 for(const item of items){if(item.targetId&&!await first(env,'SELECT id FROM kadi_records WHERE id=? AND kind=?',item.targetId,kind))fail('原资料已不存在，请作为新设计投稿');const digest=await hash(JSON.stringify([item.payload,item.blobKey,item.targetId]));const old=await first(env,'SELECT id,status FROM kadi_submissions WHERE hash=? AND actor_id=? AND kind=?',digest,user.actor_id,kind);if(old){out.push({...old,reused:true});continue}const id=uuid();writes.push(query(env,"INSERT INTO kadi_submissions(id,kind,name,payload,blob_key,thumb_key,target_id,hash,actor_id,author,status,revision,feedback,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'pending',1,'',?,?) ON CONFLICT(kind,hash,actor_id) DO NOTHING",id,kind,item.payload.name,JSON.stringify(item.payload),item.blobKey||null,item.thumbKey||null,item.targetId,digest,user.actor_id,user.name,stamp(),stamp()));out.push({id,status:'pending',revision:1})}
 if(writes.length){const gate=uuid();writes.push(query(env,"INSERT INTO kadi_guards(id,valid) VALUES(?,CASE WHEN (SELECT COUNT(*) FROM kadi_submissions WHERE status IN ('pending','needs_changes'))<=500 THEN 1 ELSE 0 END)",gate),query(env,'DELETE FROM kadi_guards WHERE id=?',gate));try{await env.DB.batch(writes)}catch(e){if(/constraint|guard/i.test(e.message))fail('待审核投稿较多，请稍后再提交',429);throw e}}return {submissions:out,message:'投稿已保存，等待审核'};
}
async function publish(env,user,kind,items,expected={},review=null){
 if(!items.length||items.length>100)fail('一次可发布 1 至 100 项');const writes=[],gates=[],out=[];
 if(review){const g=uuid();gates.push(g);writes.push(query(env,"INSERT INTO kadi_guards(id,valid) VALUES(?,CASE WHEN EXISTS(SELECT 1 FROM kadi_submissions WHERE id=? AND revision=? AND status='pending') THEN 1 ELSE 0 END)",g,review.id,review.revision))}
 const ids=new Set();for(const item of items){const id=item.targetId||kind+'.'+(await hash((review?.actor_id||user.actor_id)+':'+item.payload.id)).slice(0,24);if(!new RegExp('^'+kind+'\\.[a-f0-9]{24}$').test(id)||ids.has(id))fail('资料编号无效或同批重复');ids.add(id);const old=await first(env,'SELECT * FROM kadi_records WHERE id=?',id);if(item.targetId&&!old)fail('原资料不存在，请刷新',409);
  const payload={...item.payload,id},digest=await hash(JSON.stringify([payload,item.blobKey||null]));if(old?.hash===digest&&old.status==='published'){out.push({id,revision:old.revision,reused:true});continue}const wanted=Number(expected[id]||0);if(old&&wanted!==old.revision||!old&&wanted!==0)fail('资料已更新，请查看差异后再发布',409);
  const revision=(old?.revision||0)+1,author=old?.author||review?.author||user.name;if(old&&review)payload.contributors=[...new Set([...(JSON.parse(old.payload).contributors||[]),review.author])];
  const g=uuid();gates.push(g);writes.push(query(env,'INSERT INTO kadi_guards(id,valid) VALUES(?,CASE WHEN (SELECT revision FROM kadi_records WHERE id=?) IS ? THEN 1 ELSE 0 END)',g,id,old?.revision||null));
  writes.push(query(env,"INSERT INTO kadi_records(id,kind,name,payload,blob_key,thumb_key,hash,revision,author,status,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'published',?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,payload=excluded.payload,blob_key=excluded.blob_key,thumb_key=excluded.thumb_key,hash=excluded.hash,revision=excluded.revision,author=excluded.author,status='published',updated_at=excluded.updated_at",id,kind,payload.name,JSON.stringify(payload),item.blobKey||null,item.thumbKey||null,digest,revision,author,stamp()));
  writes.push(query(env,'INSERT INTO kadi_versions(id,record_id,revision,payload,blob_key,thumb_key,author,updated_at) VALUES(?,?,?,?,?,?,?,?)',id+':'+revision,id,revision,JSON.stringify(payload),item.blobKey||null,item.thumbKey||null,author,stamp()),audit(env,user,review?'review-publish':'publish',id));out.push({id,revision});
 }
 const capacity=uuid();gates.push(capacity);writes.push(query(env,"INSERT INTO kadi_guards(id,valid) VALUES(?,CASE WHEN (SELECT COUNT(*) FROM kadi_records WHERE kind='term')<=5000 AND (SELECT COUNT(*) FROM kadi_records WHERE kind='asset')<=2000 AND (SELECT COALESCE(SUM(length(CAST(payload AS BLOB))+500),0) FROM kadi_records WHERE kind='term')<4194304 THEN 1 ELSE 0 END)",capacity));
 if(review)writes.push(query(env,"UPDATE kadi_submissions SET status='published',updated_at=? WHERE id=?",stamp(),review.id));for(const g of gates)writes.push(query(env,'DELETE FROM kadi_guards WHERE id=?',g));
 try{await env.DB.batch(writes)}catch(e){if(/constraint|unique|guard/i.test(e.message))fail('资料或审核状态已变化，已保留原稿，请刷新',409);throw e}return {published:out,message:'已共享'};
}
async function mint(env,role,name,permissions=[],actorId=uuid(),days=3650){const raw=token();await query(env,'INSERT INTO kadi_sessions(id,actor_id,role,name,permissions,expires_at,revoked,created_at) VALUES(?,?,?,?,?,?,0,?)',await hash(raw),actorId,role,name,JSON.stringify(permissions),Date.now()+days*86400000,stamp()).run();return raw}
const visitorCookie=raw=>'kadi_visitor='+raw+'; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=31536000';
async function fileResponse(request,env,key){
 if(!/^[a-f0-9]{64}$/.test(key))fail('素材不存在',404);await canRead(request,env);const visible=await first(env,"SELECT r.id FROM kadi_versions v JOIN kadi_records r ON r.id=v.record_id WHERE r.status='published' AND (v.blob_key=? OR v.thumb_key=?) LIMIT 1",key,key);
 if(!visible){const u=await requireActor(request,env);const owned=await first(env,'SELECT id FROM kadi_submissions WHERE (blob_key=? OR thumb_key=?) AND actor_id=? LIMIT 1',key,key,u.actor_id);if(!owned&&!allowed(u,'review','asset'))fail('素材不存在',404)}const object=await env.BUCKET.get(key);if(!object)fail('素材不存在',404);return new Response(object.body,{headers:{'Content-Type':'image/png','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox",'Cache-Control':visible&&(await settings(env)).readMode==='public'?'public,max-age=3600':'private,no-store','Access-Control-Allow-Origin':'*'}})
}
export async function handleKadi(request,env){
 try{
  if(!env.DB||!env.BUCKET)fail('共享服务尚未就绪',503);const url=new URL(request.url),path=url.pathname.replace(/^\/api\/repository\/?/,'');if(['POST','DELETE','PUT'].includes(request.method)&&request.headers.get('origin')&&request.headers.get('origin')!==url.origin)fail('请从卡递资料页操作',403);
  if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':url.origin,'Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS'}});
  if(request.method==='GET'){
   if(path==='health')return json({ok:true,service:'kadi-shared-library',version:'1.0.0'});
   if(path==='session'){const u=await actor(request,env);return json({authenticated:!!u,admin:u?.role==='owner',role:u?.role||'',name:u?.name||'',permissions:u?JSON.parse(u.permissions):[],submissionMode:(await settings(env)).submissionMode})}
   if(path==='catalog')return json(await catalog(request,env));
   if(path==='glossary'){const d=await catalog(request,env);return json({schema:'cardstudio-glossary-v1',version:d.revision,source:'卡递共享词条库',terms:d.terms})}
   if(path.startsWith('files/'))return await fileResponse(request,env,path.slice(6));
   if(path==='submissions'){const u=await requireActor(request,env);let rows=(allowed(u,'review','term')||allowed(u,'review','asset'))?await all(env,"SELECT * FROM kadi_submissions WHERE status IN ('pending','needs_changes') ORDER BY created_at LIMIT 500"):await all(env,'SELECT * FROM kadi_submissions WHERE actor_id=? ORDER BY created_at DESC LIMIT 100',u.actor_id);if(u.role==='collaborator')rows=rows.filter(r=>allowed(u,'review',r.kind));return json({submissions:rows.map(r=>({...JSON.parse(r.payload),id:r.id,sourceId:JSON.parse(r.payload).id,targetId:r.target_id,kind:r.kind,author:r.author,status:r.status,submissionRevision:r.revision,feedback:r.feedback,createdAt:r.created_at,...(r.blob_key?{url:'/api/repository/files/'+r.blob_key,thumbnailUrl:'/api/repository/files/'+r.thumb_key}:{} )}))})}
   if(path==='visitor/export'){const u=await requireActor(request,env);if(!['visitor','invite-read','invite-submit'].includes(u.role))fail('此凭证不能导出到共享网页',403);return json({schema:'kadi-contribution-receipt-v1',token:rawToken(request),name:u.name})}
   if(path==='manage'){const u=await requireActor(request,env,'owner');return json({settings:await settings(env),devices:(await all(env,"SELECT id,role,name,permissions,revoked,expires_at,created_at FROM kadi_sessions WHERE role!='visitor' ORDER BY created_at DESC LIMIT 200")).map(s=>({...s,current:s.id===u.id})),hidden:(await all(env,"SELECT * FROM kadi_records WHERE status='hidden' ORDER BY updated_at DESC")).map(publicItem),audit:await all(env,"SELECT a.action,a.record_id,a.detail,a.created_at,COALESCE(r.name,s.name,'共享范围') AS name FROM kadi_audit a LEFT JOIN kadi_records r ON r.id=a.record_id LEFT JOIN kadi_submissions s ON s.id=a.record_id ORDER BY a.created_at DESC LIMIT 100"),usage:await first(env,'SELECT COUNT(*) AS records FROM kadi_records')})}
   const history=path.match(/^records\/(term\.[a-f0-9]{24}|asset\.[a-f0-9]{24})\/versions$/);if(history){await requireActor(request,env,'owner');return json({versions:(await all(env,'SELECT * FROM kadi_versions WHERE record_id=? ORDER BY revision DESC',history[1])).map(r=>({...JSON.parse(r.payload),revision:r.revision,author:r.author,updatedAt:r.updated_at,...(r.blob_key?{url:'/api/repository/files/'+r.blob_key}:{} )}))})}
  }
  if(request.method==='POST'){
   if(path==='bootstrap'){const data=await body(request);if(!env.KADI_BOOTSTRAP_HASH||await hash(str(data.bootstrap,100,'安装授权'))!==env.KADI_BOOTSTRAP_HASH)fail('安装授权无效',401);const raw=token(),id=await hash(raw);try{await env.DB.batch([query(env,"INSERT INTO kadi_settings(key,value) VALUES('bootstrap-used',?)",stamp()),query(env,"INSERT INTO kadi_sessions(id,actor_id,role,name,permissions,expires_at,revoked,created_at) VALUES(?,?,'owner','卡递创作者','[]',?,0,?)",id,uuid(),Date.now()+3650*86400000,stamp())])}catch{fail('安装授权已使用',409)}return json({token:raw})}
   if(path==='activate'){const d=await body(request),grant=await first(env,"SELECT * FROM kadi_sessions WHERE id=? AND role IN ('grant','recovery') AND revoked=0 AND expires_at>?",await hash(str(d.grant,100,'设备授权')),Date.now());if(!grant)fail('设备授权已使用、过期或失效',401);const raw=token(),g=uuid();try{await env.DB.batch([query(env,'INSERT INTO kadi_guards(id,valid) VALUES(?,CASE WHEN EXISTS(SELECT 1 FROM kadi_sessions WHERE id=? AND revoked=0) THEN 1 ELSE 0 END)',g,grant.id),query(env,'UPDATE kadi_sessions SET revoked=1 WHERE id=?',grant.id),query(env,"INSERT INTO kadi_sessions(id,actor_id,role,name,permissions,expires_at,revoked,created_at) VALUES(?,?,'owner',?,'[]',?,0,?)",await hash(raw),grant.actor_id,str(d.name||'卡递完整版',80,'设备名称'),Date.now()+3650*86400000,stamp()),query(env,'DELETE FROM kadi_guards WHERE id=?',g)])}catch{fail('设备授权已使用',409)}return json({token:raw})}
   if(path==='visitor'){const d=await body(request),name=str(d.name,60,'昵称').trim();if(!name)fail('请填写昵称');const existing=await actor(request,env);if(existing){await query(env,'UPDATE kadi_sessions SET name=? WHERE id=?',name,existing.id).run();return json({ok:true,name})}await quota(env,'new-session:'+await hash(request.headers.get('cf-connecting-ip')||'unknown'),1,300);const raw=await mint(env,'visitor',name,[],uuid(),365);return json({ok:true,name},200,{'Set-Cookie':visitorCookie(raw)})}
   if(path==='visitor/restore'){const d=await body(request),u=await first(env,"SELECT * FROM kadi_sessions WHERE id=? AND role IN ('visitor','invite-read','invite-submit','collaborator') AND revoked=0 AND expires_at>?",await hash(str(d.token,100,'投稿凭证')),Date.now());if(!u)fail('投稿凭证无效',401);return json({ok:true,name:u.name},200,{'Set-Cookie':visitorCookie(d.token)})}
   if(path==='devices/enroll'||path==='devices/recovery'||path==='devices/invite'){const u=await requireActor(request,env,'owner'),d=await body(request),role=path.endsWith('recovery')?'recovery':path.endsWith('enroll')?'grant':d.role;if(!['recovery','grant','invite-read','invite-submit','collaborator'].includes(role))fail('授权类型无效');const permissions=role==='collaborator'&&Array.isArray(d.permissions)?d.permissions.filter(p=>['review','publish','review:term','review:asset','publish:term','publish:asset'].includes(p)):[];const raw=await mint(env,role,str(d.name||'新授权',80,'名称'),permissions,role==='grant'||role==='recovery'?u.actor_id:uuid(),role==='grant'?365:3650);return json({token:raw,role})}
   if(path==='devices/revoke'){const u=await requireActor(request,env,'owner'),d=await body(request);if(d.id===u.id)fail('请先在另一台管理设备确认授权，再撤销当前设备');await env.DB.batch([query(env,'UPDATE kadi_sessions SET revoked=1 WHERE id=?',str(d.id,64,'授权编号')),audit(env,u,'revoke-device',null)]);return json({ok:true})}
   if(path==='settings'){const u=await requireActor(request,env,'owner'),d=await body(request);if(!['open','invite','closed'].includes(d.submissionMode)||!['public','invite'].includes(d.readMode))fail('共享范围无效');await env.DB.batch([query(env,"INSERT INTO kadi_settings(key,value) VALUES('policy',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",JSON.stringify({submissionMode:d.submissionMode,readMode:d.readMode})),audit(env,u,'policy',null)]);return json({ok:true})}
   if(path==='terms/publish'||path==='terms/submit'){const publishing=path.endsWith('publish'),u=await requireActor(request,env,publishing?'publish':null,'term'),d=await body(request);if(!Array.isArray(d.terms)||d.terms.length>100)fail('词条数量无效');const items=d.terms.map(t=>termItem(t,u));return json(publishing?await publish(env,u,'term',items,d.expectedRevisions||{}):await submit(request,env,u,'term',items))}
   if(path==='assets/publish'||path==='assets/submit'){const publishing=path.endsWith('publish'),u=await requireActor(request,env,publishing?'publish':null,'asset');if(!publishing){await permitSubmission(request,env,u,1);if((await first(env,"SELECT COUNT(*) AS count FROM kadi_submissions WHERE status IN ('pending','needs_changes')")).count>=500)fail('待审核投稿较多，请稍后再提交',429)}const item=await assetItem(request,env,u);return json(publishing?await publish(env,u,'asset',[item],item.expected):await submit(request,env,u,'asset',[item],true))}
   const review=path.match(/^review\/([a-f0-9-]{36})$/);if(review){const u=await requireActor(request,env),d=await body(request),row=await first(env,'SELECT * FROM kadi_submissions WHERE id=?',review[1]);if(!row||!allowed(u,'review',row.kind))fail('没有这份投稿的审核权限',403);if(row.status!=='pending'||d.submissionRevision!==row.revision)fail('投稿已变化，请重新查看',409);if(d.decision==='publish'){if(!allowed(u,'publish',row.kind))fail('此授权仅能预审，不能发布',403);return json(await publish(env,u,row.kind,[{payload:JSON.parse(row.payload),blobKey:row.blob_key,thumbKey:row.thumb_key,targetId:row.target_id}],d.expectedRevisions||{},row))}if(!['reject','needs_changes'].includes(d.decision))fail('审核操作无效');const feedback=str(d.feedback,2000,'反馈');if(d.decision==='needs_changes'&&!feedback.trim())fail('请写明需要补充什么');const changed=await query(env,'UPDATE kadi_submissions SET status=?,feedback=?,updated_at=? WHERE id=? AND revision=? AND status=\'pending\'',d.decision==='reject'?'rejected':'needs_changes',feedback,stamp(),row.id,row.revision).run();if(changed.meta.changes!==1)fail('投稿状态已变化',409);await audit(env,u,d.decision,row.id,feedback).run();return json({ok:true})}
   const revise=path.match(/^submissions\/([a-f0-9-]{36})\/(withdraw|resubmit)$/);if(revise){const u=await requireActor(request,env),d=await body(request),row=await first(env,'SELECT * FROM kadi_submissions WHERE id=? AND actor_id=?',revise[1],u.actor_id);if(!row||!['pending','needs_changes'].includes(row.status)||d.submissionRevision!==row.revision)fail('投稿状态已变化或不属于你',409);if(revise[2]==='withdraw'){const changed=await query(env,"UPDATE kadi_submissions SET status='withdrawn',revision=revision+1,updated_at=? WHERE id=? AND revision=? AND status IN ('pending','needs_changes')",stamp(),row.id,row.revision).run();if(changed.meta.changes!==1)fail('投稿已变化',409);return json({ok:true})}if(row.kind==='asset'){const raw=d.asset||{},name=str(raw.name||row.name,120,'素材名称').trim(),payload={...JSON.parse(row.payload),name,description:str(raw.description,4000,'说明'),tags:str(raw.tags,500,'标签'),source:str(raw.source,1000,'来源'),license:str(raw.license||'允许用于卡递作品，保留署名',500,'使用范围')};await permitSubmission(request,env,u,1);const digest=await hash(JSON.stringify([payload,row.blob_key,row.target_id]));const changed=await query(env,"UPDATE kadi_submissions SET payload=?,name=?,hash=?,status='pending',feedback='',revision=revision+1,updated_at=? WHERE id=? AND revision=? AND status IN ('pending','needs_changes')",JSON.stringify(payload),name,digest,stamp(),row.id,row.revision).run();if(changed.meta.changes!==1)fail('投稿已变化',409);return json({ok:true})}await permitSubmission(request,env,u,1);const item=termItem({...d.term,targetId:row.target_id},u),digest=await hash(JSON.stringify([item.payload,null,item.targetId]));const changed=await query(env,"UPDATE kadi_submissions SET payload=?,name=?,hash=?,status='pending',feedback='',revision=revision+1,updated_at=? WHERE id=? AND revision=? AND status IN ('pending','needs_changes')",JSON.stringify(item.payload),item.payload.name,digest,stamp(),row.id,row.revision).run();if(changed.meta.changes!==1)fail('投稿已变化',409);return json({ok:true})}
   const record=path.match(/^records\/(term\.[a-f0-9]{24}|asset\.[a-f0-9]{24})\/(state|rollback)$/);if(record){const u=await requireActor(request,env,'owner'),d=await body(request),old=await first(env,'SELECT * FROM kadi_records WHERE id=?',record[1]);if(!old||old.revision!==d.expectedRevision)fail('共享资料已变化，请刷新',409);if(record[2]==='rollback'){const version=await first(env,'SELECT * FROM kadi_versions WHERE record_id=? AND revision=?',old.id,d.revision);if(!version)fail('历史版本不存在');return json(await publish(env,u,old.kind,[{payload:JSON.parse(version.payload),blobKey:version.blob_key,thumbKey:version.thumb_key,targetId:old.id}],{[old.id]:old.revision}))}if(!['hide','restore'].includes(d.action))fail('操作无效');const g=uuid();await env.DB.batch([query(env,'INSERT INTO kadi_guards(id,valid) VALUES(?,CASE WHEN EXISTS(SELECT 1 FROM kadi_records WHERE id=? AND revision=?) THEN 1 ELSE 0 END)',g,old.id,d.expectedRevision),query(env,'UPDATE kadi_records SET status=?,revision=revision+1,updated_at=? WHERE id=?',d.action==='hide'?'hidden':'published',stamp(),old.id),audit(env,u,d.action,old.id),query(env,'DELETE FROM kadi_guards WHERE id=?',g)]);return json({ok:true})}
   if(path==='backup'){const u=await requireActor(request,env,'owner');return json({schema:'kadi-shared-backup-v1',createdAt:stamp(),records:await all(env,'SELECT * FROM kadi_records'),versions:await all(env,'SELECT * FROM kadi_versions'),submissions:await all(env,'SELECT * FROM kadi_submissions'),settings:await settings(env),audit:await all(env,'SELECT * FROM kadi_audit')})}
  }
  fail('资料库接口不存在',404);
 }catch(error){return json({error:error.status?error.message:'共享服务暂时不可用，原资料已保留'},error.status||500)}
}
