import assert from 'node:assert/strict';
import fs from 'node:fs';
import {handleKadi,hash} from '../app/kadi-api.mjs';
import {setWebpModule,sanitizeImage} from '../app/image-codec.mjs';
import {PNG} from 'pngjs';
import jpeg from 'jpeg-js';
import {makeStorage} from './storage.mjs';
await setWebpModule(await WebAssembly.compile(fs.readFileSync(new URL('../node_modules/@jsquash/webp/codec/dec/webp_dec.wasm',import.meta.url))));
const storage=makeStorage(),env={...storage,KADI_BOOTSTRAP_HASH:await hash('qa-bootstrap')},results=[];
async function call(path,body,headers={},method){const r=await handleKadi(new Request('https://kadi.test/api/repository/'+path,{method:method||(body!==undefined?'POST':'GET'),headers:{...headers,...(body!==undefined&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:body instanceof FormData?body:JSON.stringify(body)}:{})}),env);return {status:r.status,response:r,data:r.headers.get('content-type')?.includes('application/json')?await r.json():null}}
async function test(name,fn){await fn();results.push({name,ok:true})}
const term={id:'qa.original',name:'自检词条（不会上线）',description:'原规则定义',color:'#236a46',category:'触发',tags:'测试',aliases:['别名'],example:'完整示例',designNotes:'完整设计说明',namespace:'规则甲',secret:'PRIVATE_MUST_NOT_LEAK',cards:['PRIVATE_MUST_NOT_LEAK']};let owner,guest,guest2,termId,subId,assetSubId,assetId,assetUrl,receipt;
const pixels=Buffer.from([255,255,255,0,0,0,0,255,200,20,30,90,50,60,70,255]);const png=PNG.sync.write({width:2,height:2,data:pixels});
function image(bytes=png,metadata={}){const form=new FormData();form.set('file',new Blob([bytes],{type:'image/png'}),'picture.png');form.set('metadata',JSON.stringify({id:'qa.image',name:'自检图片（不会上线）',category:'frame',description:'原图说明',...metadata}));return form}
await test('首次设备授权只使用一次，GPT 身份头不能获取管理权限',async()=>{const r=await call('bootstrap',{bootstrap:'qa-bootstrap',name:'卡递创作者'});assert.equal(r.status,200);owner={Authorization:'Bearer '+r.data.token};assert.equal((await call('bootstrap',{bootstrap:'qa-bootstrap'})).status,409);assert.equal((await call('session',undefined,{'oai-authenticated-user-email':'owner@example.test','oai-authenticated-user-id':'owner'})).data.admin,false)});
await test('浏览不登录；访客只填昵称；凭证能恢复自己的投稿',async()=>{assert.equal((await call('catalog')).status,200);const r=await call('visitor',{name:'投稿伙伴'});assert.equal(r.status,200);guest={Cookie:r.response.headers.get('set-cookie').split(';')[0]};assert.equal((await call('session',undefined,guest)).data.name,'投稿伙伴');receipt=(await call('visitor/export',undefined,guest)).data;const restored=await call('visitor/restore',{token:receipt.token});assert.equal(restored.status,200);guest2={Cookie:(await call('visitor',{name:'其他伙伴'})).response.headers.get('set-cookie').split(';')[0]}});
await test('访客不能发布、读取管理记录或其他人的投稿，跨站请求被拦截',async()=>{assert.equal((await call('terms/publish',{terms:[term]},guest)).status,403);assert.equal((await call('manage',undefined,guest)).status,403);assert.equal((await call('terms/submit',{terms:[term]},{...guest,Origin:'https://other.test'})).status,403)});
await test('直接共享保留完整定义和署名，过滤项目与私密字段',async()=>{const r=await call('terms/publish',{terms:[term]},owner);assert.equal(r.status,200);termId=r.data.published[0].id;const d=(await call('catalog')).data.terms[0];assert.equal(d.example,term.example);assert.equal(d.designNotes,term.designNotes);assert.deepEqual(d.aliases,term.aliases);assert.equal(d.namespace,'规则甲');assert.ok(!JSON.stringify(d).includes('PRIVATE_MUST_NOT_LEAK'))});
await test('同名不同定义可以共存；空发布不会清空；失败批次不部分写入',async()=>{assert.equal((await call('terms/publish',{terms:[{...term,id:'qa.other',description:'完全不同的规则',namespace:'规则乙'}]},owner)).status,200);assert.equal((await call('catalog')).data.terms.length,2);assert.equal((await call('terms/publish',{terms:[]},owner)).status,400);assert.equal((await call('terms/publish',{terms:[{...term,id:'qa.new',name:'不应写入'}, {...term,description:'并发变更'}]},owner)).status,409);assert.equal((await call('catalog')).data.terms.length,2)});
await test('重复发布幂等，旧版本更新必须拒绝；历史快照保留',async()=>{assert.equal((await call('terms/publish',{terms:[term]},owner)).data.published[0].reused,true);assert.equal((await call('terms/publish',{terms:[{...term,targetId:termId,description:'二版'}],expectedRevisions:{[termId]:1}},owner)).status,200);assert.equal((await call('terms/publish',{terms:[{...term,targetId:termId,description:'陈旧编辑'}],expectedRevisions:{[termId]:1}},owner)).status,409);const history=(await call('records/'+termId+'/versions',undefined,owner)).data.versions;assert.equal(history.length,2);assert.equal(history[1].description,'原规则定义')});
await test('投稿等待审核，重复投稿不堆积，其他伙伴不可见',async()=>{const proposal={...term,id:'qa.contribution',name:'伙伴新规则'};const r=await call('terms/submit',{terms:[proposal]},guest);assert.equal(r.status,200);subId=r.data.submissions[0].id;assert.equal((await call('terms/submit',{terms:[proposal]},guest)).data.submissions[0].id,subId);assert.equal((await call('submissions',undefined,guest2)).data.submissions.length,0);assert.equal((await call('catalog')).data.terms.length,2)});
await test('审核退回给出反馈，原投稿修改重交，陈旧审核不能发布',async()=>{assert.equal((await call('review/'+subId,{decision:'needs_changes',submissionRevision:1,feedback:'请补充触发时机'},owner)).status,200);assert.equal((await call('submissions',undefined,guest)).data.submissions[0].feedback,'请补充触发时机');assert.equal((await call('submissions/'+subId+'/resubmit',{submissionRevision:1,term:{...term,id:'qa.contribution',name:'伙伴新规则',description:'补充后的完整定义'}},guest)).status,200);assert.equal((await call('review/'+subId,{decision:'publish',submissionRevision:1},owner)).status,409);assert.equal((await call('review/'+subId,{decision:'publish',submissionRevision:2},owner)).status,200);assert.equal((await call('catalog')).data.terms.find(x=>x.name==='伙伴新规则').author,'投稿伙伴')});
await test('真实图片解码重新编码，保留 alpha；伪装图片和过大尺寸拒绝',async()=>{const clean=await sanitizeImage(png);assert.deepEqual(PNG.sync.read(Buffer.from(clean.clean)).data,pixels);assert.equal((await call('assets/submit',image(Buffer.from('<svg onload="x">')),guest)).status,400);const altered=Buffer.from(png);altered.writeUInt32BE(100000,16);await assert.rejects(()=>sanitizeImage(altered));const r=await call('assets/submit',image(),guest);assert.equal(r.status,200);assetSubId=r.data.submissions[0].id;const q=(await call('submissions',undefined,owner)).data.submissions.find(x=>x.id===assetSubId);assetUrl=q.url;assert.equal((await call(assetUrl.split('/api/repository/')[1])).status,401);assert.equal((await call(assetUrl.split('/api/repository/')[1],undefined,guest2)).status,404);assert.equal((await call(assetUrl.split('/api/repository/')[1],undefined,owner)).status,200)});
await test('图片补充说明沿用原投稿；审核后公开图片与来源可读取',async()=>{assert.equal((await call('review/'+assetSubId,{decision:'needs_changes',submissionRevision:1,feedback:'请写明来源'},owner)).status,200);assert.equal((await call('submissions/'+assetSubId+'/resubmit',{submissionRevision:1,asset:{name:'补充来源的图片',description:'详细说明',source:'伙伴原创'}},guest)).status,200);const r=await call('review/'+assetSubId,{decision:'publish',submissionRevision:2},owner);assert.equal(r.status,200);assetId=r.data.published[0].id;assert.equal((await call(assetUrl.split('/api/repository/')[1])).status,200);assert.equal((await call('catalog')).data.assets[0].source,'伙伴原创')});
await test('JPG 与 WebP 解码可用，透明框原始像素完整保留',async()=>{const encoded=jpeg.encode({width:2,height:2,data:pixels},90);const result=await sanitizeImage(encoded.data);assert.equal(result.width,2);const webp=fs.readFileSync(new URL('./fixtures/test.webp',import.meta.url));assert.equal((await sanitizeImage(webp)).mime,'image/png');const original=fs.readFileSync(new URL('./fixtures/original-frame.png',import.meta.url));const safe=await sanitizeImage(original);assert.deepEqual(PNG.sync.read(Buffer.from(safe.clean)).data,PNG.sync.read(original).data)});
await test('协作者只能审核指定资料，不能发布、授权或查看完整管理',async()=>{const invite=await call('devices/invite',{name:'词条预审',role:'collaborator',permissions:['review:term']},owner);const headers={Authorization:'Bearer '+invite.data.token};assert.equal((await call('visitor/restore',{token:invite.data.token})).status,200);const r=await call('terms/submit',{terms:[{...term,id:'qa.pending',name:'预审词条'}]},guest);const id=r.data.submissions[0].id;assert.equal((await call('submissions',undefined,headers)).data.submissions.every(x=>x.kind==='term'),true);assert.equal((await call('review/'+id,{decision:'publish',submissionRevision:1},headers)).status,403);assert.equal((await call('review/'+id,{decision:'needs_changes',submissionRevision:1,feedback:'补充'},headers)).status,200);assert.equal((await call('devices/enroll',{name:'越权'},headers)).status,403)});
await test('下架停止公开取用，可恢复；回滚新建修订，不改旧历史',async()=>{assert.equal((await call('records/'+assetId+'/state',{action:'hide',expectedRevision:1},owner)).status,200);assert.equal((await call(assetUrl.split('/api/repository/')[1])).status,401);assert.equal((await call('records/'+assetId+'/state',{action:'restore',expectedRevision:2},owner)).status,200);assert.equal((await call('records/'+termId+'/rollback',{revision:1,expectedRevision:2},owner)).status,200);assert.equal((await call('records/'+termId+'/versions',undefined,owner)).data.versions.length,3)});
await test('一键暂停投稿不影响浏览；仅邀请浏览不能被普通昵称绕过',async()=>{assert.equal((await call('settings',{readMode:'public',submissionMode:'closed'},owner)).status,200);assert.equal((await call('terms/submit',{terms:[term]},guest)).status,403);assert.equal((await call('catalog')).status,200);await call('settings',{readMode:'invite',submissionMode:'invite'},owner);assert.equal((await call('catalog',undefined,guest)).status,401);const invite=await call('devices/invite',{name:'浏览伙伴',role:'invite-read'},owner);const headers={Authorization:'Bearer '+invite.data.token};assert.equal((await call('catalog',undefined,headers)).status,200);assert.equal((await call('terms/submit',{terms:[term]},headers)).status,403)});
await test('新增管理电脑免账号授权，单次安装授权复用被拒绝，撤销立即失效',async()=>{const grant=await call('devices/enroll',{name:'另一电脑'},owner);const r=await call('activate',{grant:grant.data.token,name:'新电脑'});assert.equal(r.status,200);assert.equal((await call('activate',{grant:grant.data.token})).status,401);const headers={Authorization:'Bearer '+r.data.token};assert.equal((await call('session',undefined,headers)).data.admin,true);const id=await hash(r.data.token);await call('devices/revoke',{id},owner);assert.equal((await call('manage',undefined,headers)).status,401)});
await test('完整资料备份不导出设备或访客令牌',async()=>{const d=(await call('backup',{},owner)).data;assert.equal(d.schema,'kadi-shared-backup-v1');assert.ok(d.versions.length);assert.ok(d.submissions.length);assert.ok(!JSON.stringify(d).includes(receipt.token));assert.equal(d.sessions,undefined)});
await test('素材按二进制去重计费；超出存储预算不会写文件或新增记录',async()=>{const before=storage.files.size,charged=()=>storage.sql.prepare("SELECT SUM(CAST(value AS INTEGER)) AS n FROM kadi_settings WHERE key LIKE 'stored-image:%'").get().n;const initial=charged();assert.equal((await call('assets/publish',image(png,{id:'qa.duplicate',name:'同像素另一署名'}),owner)).status,200);assert.equal(storage.files.size,before);assert.equal(charged(),initial);storage.sql.prepare('INSERT INTO kadi_settings(key,value) VALUES(?,?)').run('stored-image:test-capacity','536870912');const other=PNG.sync.write({width:1,height:1,data:Buffer.from([21,45,90,180])});const count=(await call('catalog',undefined,owner)).data.assets.length;assert.equal((await call('assets/publish',image(other,{id:'qa.over-budget'}),owner)).status,429);assert.equal(storage.files.size,before);assert.equal((await call('catalog',undefined,owner)).data.assets.length,count);assert.equal(charged(),initial+536870912);storage.sql.prepare('DELETE FROM kadi_settings WHERE key=?').run('stored-image:test-capacity')});
await test('更换昵称不能绕过同一来源的每日投稿限额',async()=>{await call('settings',{readMode:'public',submissionMode:'open'},owner);const ip={'cf-connecting-ip':'198.51.100.25'},terms=Array.from({length:40},(_,i)=>({...term,id:'qa.quota.'+i,name:'限额测试 '+i}));for(let i=0;i<5;i++){const v=await call('visitor',{name:'限额测试 '+i},ip);const headers={...ip,Cookie:v.response.headers.get('set-cookie').split(';')[0]};assert.equal((await call('terms/submit',{terms},headers)).status,200)}const v=await call('visitor',{name:'又一昵称'},ip),headers={...ip,Cookie:v.response.headers.get('set-cookie').split(';')[0]};assert.equal((await call('terms/submit',{terms:[term]},headers)).status,429)});
await test('审核队列已满时拒绝图片，不留下新对象',async()=>{const count=storage.sql.prepare("SELECT COUNT(*) AS n FROM kadi_submissions WHERE status IN ('pending','needs_changes')").get().n;const insert=storage.sql.prepare("INSERT INTO kadi_submissions(id,kind,name,payload,hash,actor_id,author,status,revision,feedback,created_at,updated_at) VALUES(?,'term','容量测试','{}',?,'capacity-test','自检','pending',1,'','2026-01-01','2026-01-01')");for(let i=count;i<500;i++)insert.run('capacity-'+i,'capacity-'+i);const before=storage.files.size;assert.equal((await call('assets/submit',image(),guest2)).status,429);assert.equal(storage.files.size,before)});
fs.mkdirSync(new URL('../verification/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('../verification/kadi-api-results.json',import.meta.url),JSON.stringify({createdAt:new Date().toISOString(),checks:results},null,2));console.log('卡递共享服务 '+results.length+' 项行为检查通过。');
