import assert from 'node:assert/strict';
import fs from 'node:fs';
import {handleRepository} from '../app/repository-api.mjs';
import {makeStorage} from './storage.mjs';
const store=makeStorage(),env={...store,ADMIN_EMAIL:'owner@example.test'},results=[];
store.sql.prepare('INSERT INTO sessions(id,actor_id,expires_at) VALUES(?,?,?)').run(Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('test-local-owner'))).toString('hex'),'test-owner',Date.now()+3600000);
const owner={authorization:'Bearer test-local-owner'},contributor={'oai-authenticated-user-id':'contributor-a','oai-authenticated-user-email':'a@example.test','oai-authenticated-user-full-name':encodeURIComponent('共创作者甲')},other={'oai-authenticated-user-id':'contributor-b','oai-authenticated-user-email':'b@example.test'};
async function call(path,body,headers={},method){const request=new Request('https://repository.test/api/repository/'+path,{method:method||(body?'POST':'GET'),headers:{...headers,...(body&&! (body instanceof FormData)?{'Content-Type':'application/json'}:{})},...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});const response=await handleRepository(request,env);return {status:response.status,response,data:response.headers.get('content-type')?.includes('application/json')?await response.json():null}}
async function test(name,fn){await fn();results.push({name,ok:true})}
const term={id:'local.term',name:'验证・协作',color:'#5639df',category:'触发',tags:'共创,版本',description:'完整定义：造成伤害后触发。',aliases:['合作'],example:'协作 2：造成两点伤害。',designNotes:'同一次事件只触发一次。',privateProject:'MUST_NOT_PUBLISH',key:'MUST_NOT_PUBLISH'};
let termId,submission,assetSubmission,assetId,oldUrl;
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aS9sAAAAASUVORK5CYII=','base64');
function image(name='验证图片',bytes=png,expected={}){const form=new FormData();form.set('file',new Blob([bytes],{type:'image/png'}),'file.png');form.set('metadata',JSON.stringify({name,category:'icon',tags:'协作',description:'完整素材说明',expectedRevisions:expected}));return form}
await test('匿名能读取真实空仓库，不能发布或投稿',async()=>{assert.equal((await call('catalog')).data.terms.length,0);assert.equal((await call('terms/publish',{terms:[term]})).status,401);assert.equal((await call('terms/submit',{terms:[term]})).status,401)});
await test('跨站投稿被拒绝',async()=>assert.equal((await call('terms/submit',{terms:[term]},{...contributor,Origin:'https://other.test'})).status,403));
await test('贡献者无法直接发布和审核',async()=>{assert.equal((await call('terms/publish',{terms:[term]},contributor)).status,403);assert.equal((await call('pair',{challenge:'a'.repeat(43),state:'b'.repeat(24)},contributor)).status,403)});
await test('私人版发布完整设计，过滤项目和密钥',async()=>{const out=await call('terms/publish',{terms:[term]},owner);assert.equal(out.status,200);termId=out.data.published[0].id;const data=(await call('catalog')).data;assert.equal(data.terms[0].example,term.example);assert.equal(data.terms[0].designNotes,term.designNotes);assert.deepEqual(data.terms[0].aliases,term.aliases);assert.ok(!JSON.stringify(data).includes('MUST_NOT_PUBLISH'));assert.equal(data.terms[0].publicRevision,1)});
await test('重复发布幂等；陈旧版本更新被拒绝',async()=>{assert.equal((await call('terms/publish',{terms:[term]},owner)).data.published[0].reused,true);assert.equal((await call('terms/publish',{terms:[{...term,description:'第二版'}]},owner)).status,409)});
await test('多项发布失败不产生部分写入',async()=>{const out=await call('terms/publish',{terms:[{...term,id:'new',name:'不应写入'}, {...term,description:'冲突'}]},owner);assert.equal(out.status,409);assert.equal((await call('catalog')).data.terms.length,1)});
await test('社区词条投稿不会直接进入公开库，重复投稿复用',async()=>{const proposal={...term,description:'社区改进后的完整定义'};const out=await call('terms/submit',{terms:[proposal]},contributor);assert.equal(out.status,200);submission=out.data.submissions[0].id;assert.equal((await call('terms/submit',{terms:[proposal]},contributor)).data.submissions[0].id,submission);assert.equal((await call('catalog')).data.terms[0].description,term.description);assert.equal((await call('submissions',null,other)).data.submissions.length,0);assert.equal((await call('submissions',null,owner)).data.submissions[0].designNotes,term.designNotes)});
await test('私人版采用投稿并发布新版，两版取得同一内容',async()=>{const out=await call('review/'+submission,{decision:'publish',expectedRevisions:{[termId]:1}},owner);assert.equal(out.status,200);assert.equal((await call('catalog')).data.terms[0].publicRevision,2);assert.equal((await call('catalog')).data.terms[0].author,'共创作者甲');assert.equal((await call('glossary')).data.terms[0].description,'社区改进后的完整定义');assert.equal((await call('review/'+submission,{decision:'publish'},owner)).status,409)});
await test('HTML 伪装图片被拒绝',async()=>assert.equal((await call('assets/submit',image('bad',Buffer.from('<svg onload="alert(1)">')),contributor)).status,400));
await test('社区素材上传；未审图片仅作者和管理员能查看',async()=>{const out=await call('assets/submit',image(),contributor);assert.equal(out.status,200);assetSubmission=out.data.submissions[0].id;const item=(await call('submissions',null,owner)).data.submissions.find(x=>x.id===assetSubmission);oldUrl=item.url;assert.equal((await call(oldUrl.split('/api/repository/')[1])).status,401);assert.equal((await call(oldUrl.split('/api/repository/')[1],null,other)).status,404);assert.equal((await call(oldUrl.split('/api/repository/')[1],null,contributor)).status,200);assert.equal((await call('catalog')).data.assets.length,0)});
await test('素材审核发布，公开下载原文件逐字节一致',async()=>{const out=await call('review/'+assetSubmission,{decision:'publish'},owner);assert.equal(out.status,200);assetId=out.data.published[0].id;const asset=(await call('catalog')).data.assets[0];assert.equal(asset.description,'完整素材说明');assert.equal(asset.width,1);const outFile=await call(asset.url.split('/api/repository/')[1]);assert.deepEqual(Buffer.from(await outFile.response.arrayBuffer()),png);assert.equal(outFile.response.headers.get('access-control-allow-origin'),'*')});
await test('更新图片不会破坏旧项目的固定版本',async()=>{const png2=Buffer.from(png);png2[png2.length-10]^=1;const out=await call('assets/publish',image('验证图片',png2,{[assetId]:1}),owner);assert.equal(out.status,200);assert.equal((await call('catalog')).data.assets[0].publicRevision,2);assert.equal((await call(oldUrl.split('/api/repository/')[1])).status,200)});
await test('拒绝投稿不改变公共内容',async()=>{const out=await call('terms/submit',{terms:[{...term,name:'未采用'}]},contributor);const id=out.data.submissions[0].id;assert.equal((await call('review/'+id,{decision:'reject'},owner)).status,200);assert.equal((await call('catalog')).data.terms.length,1)});
await test('一次性 PKCE 连接码校验且不能重放；注销立即失效',async()=>{const verifier='a'.repeat(64),hash=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))),challenge=Buffer.from(hash).toString('base64url'),state='state'.repeat(6),pair=await call('pair',{state,challenge},owner);assert.equal(pair.status,200);assert.equal((await call('token',{code:pair.data.code,state,verifier:'b'.repeat(64)})).status,401);const token=await call('token',{code:pair.data.code,state,verifier});assert.equal(token.status,200);assert.equal((await call('token',{code:pair.data.code,state,verifier})).status,401);const bearer={authorization:'Bearer '+token.data.token};assert.equal((await call('session',null,bearer)).data.admin,true);await call('logout',{},bearer);assert.equal((await call('session',null,bearer)).data.admin,false)});
await test('投稿限额不允许绕过',async()=>{const many=Array.from({length:41},(_,i)=>({...term,id:'batch.'+i,name:'量'+i}));assert.equal((await call('terms/submit',{terms:many},other)).status,429);assert.equal(store.sql.prepare('SELECT COUNT(*) AS n FROM submissions WHERE actor_id=?').get('contributor-b').n,0)});
await test('容量超限整批回滚，旧资料保持可用',async()=>{const insert=store.sql.prepare('INSERT INTO records VALUES(?,?,?,?,?,?,?,?,?,?)');for(let i=0;i<180;i++)insert.run('cap.'+i,'term','cap.'+i,'容量'+i,' '.repeat(24000),null,'cap',1,'test','');const before=store.sql.prepare('SELECT COUNT(*) AS n FROM records').get().n;assert.equal((await call('terms/publish',{terms:[{...term,name:'越界新条'}]},owner)).status,409);assert.equal(store.sql.prepare('SELECT COUNT(*) AS n FROM records').get().n,before);store.sql.prepare("DELETE FROM records WHERE id LIKE 'cap.%'").run()});
assert.equal(store.sql.prepare('SELECT COUNT(*) AS n FROM mutation_guards').get().n,0);
console.log(JSON.stringify({ok:true,tests:results},null,2));
